quarkus:
  http:
    port: 8081
    root-path: /car-dealer/v1
  swagger-ui:
    path: /swagger-ui
    always-include: true
  datasource:
    db-kind: h2
    username: sa
    password:
    jdbc:
      url: jdbc:h2:mem:testdb
  hibernate-orm:
    dialect: org.hibernate.dialect.H2Dialect
    sql-load-script: db/testdata.sql
    database:
      generation: drop-and-create
    log:
      sql: true